
// This file was generated by Prisma and assumes you have installed the following:
// npm install --save-dev prisma dotenv
import "dotenv/config";
import { defineConfig } from "prisma/config";

// Client generation does not connect to PostgreSQL. A syntactically valid
// fallback keeps `npm install` usable before a developer creates `.env.local`;
// migrate, seed, and the application still require a reachable database.
const databaseUrl =
  process.env.DATABASE_URL ??
  "postgresql://governance_compass:governance_compass@localhost:5433/governance_compass";

export default defineConfig({
  schema: "prisma/schema.prisma",
  migrations: {
    path: "prisma/migrations",
    seed: "tsx prisma/seed.ts",
  },
  engine: "classic",
  datasource: {
    url: databaseUrl,
  },
});
