import Link from "next/link";
import fs from "node:fs";
import path from "node:path";

interface DownloadMeta {
  fileSizeBytes: number;
  version: string;
  path: string;
}

const downloadMeta: DownloadMeta = JSON.parse(
  fs.readFileSync(
    path.join(process.cwd(), "public/study/derived/download_meta.json"),
    "utf8"
  )
);

function formatFileSize(bytes: number): string {
  const mb = bytes / (1024 * 1024);
  if (mb >= 10) {
    return `~${Math.round(mb)} MB`;
  }
  return `~${mb.toFixed(1)} MB`;
}

const fileSizeLabel = formatFileSize(downloadMeta.fileSizeBytes);

const DEEP_LINKS = [
  {
    href: "/study/personas",
    title: "Personas",
    description:
      "Browse all 1,002 individually, filter by region or attribute, view full profiles.",
  },
  {
    href: "/study/patterns",
    title: "Patterns",
    description:
      "Cluster characterization, archetype distribution, regional and demographic aggregates, axis-level distributions, correlations.",
  },
  {
    href: "/study/model-agreement",
    title: "Model Agreement",
    description:
      "Where Claude and Gemini converged, where they split, and on which axes the split patterns with persona attributes.",
  },
];

export default function StudyOverviewPage() {
  return (
    <main className="min-h-screen px-4 py-12">
      <article className="mx-auto max-w-2xl">
        <p className="text-[11px] uppercase tracking-[0.08em] text-text-tertiary font-medium mb-1">
          Synthetic Study
        </p>
        <h1 className="text-[28px] font-serif font-medium text-text-primary leading-tight mb-8">
          The Synthetic Study
        </h1>

        <div className="space-y-10 text-sm text-text-secondary leading-relaxed">
          {/* Intro paragraph */}
          <p>
            In April 2026, we asked a language model to generate biographies for 1,002 fictional
            people, administered the Governance Compass to each via two different models, and
            clustered the results. This section makes that dataset available for browsing,
            analysis, and download.
          </p>

          {/* Section: How it was built */}
          <section>
            <h2 className="text-[18px] font-serif font-medium text-text-primary mb-3">
              How it was built
            </h2>
            <div className="space-y-4">
              <p>
                The 1,002 personas were generated by Google&apos;s Gemini 2.5 Flash, stratified
                across ten regions: Western Europe, Eastern Europe and Central Asia, East Asia,
                Latin America, the Middle East and North Africa, sub-Saharan Africa, North America,
                South and Southeast Asia, Oceania small states, and a transnational diaspora
                category. Each persona came with a biographical narrative, demographic attributes
                (age, gender, occupation, education, economic position, religious tradition,
                governance experience), and a statement of the tensions the persona carries.
              </p>
              <p>
                The instrument was administered twice to 150 personas &mdash; once by Claude Sonnet
                4.6, once by Gemini 2.5 Flash &mdash; and once to the remaining 852, split evenly
                between the two models. That produced 1,152 administrations across 1,002 personas:
                576 by Claude, 576 by Gemini, 150 shared.
              </p>
              <p>
                Scored profiles were clustered in the 12-dimensional axis space using k-means. Six
                clusters emerged as the silhouette peak across k=6 through k=18. Those six clusters
                were then compared against the twelve hand-crafted archetypes; the comparison
                informed the archetype revision documented on the Archetypes page.
              </p>
            </div>
          </section>

          {/* Section: What this study can support */}
          <section>
            <h2 className="text-[18px] font-serif font-medium text-text-primary mb-3">
              What this study can support
            </h2>
            <div className="space-y-4">
              <p>
                The clusters are empirical &mdash; they emerge from the scored axis profiles, not
                from theoretical archetype definitions. Which hand-crafted archetypes survive
                contact with the data, and which get revised, can be asked and answered.
              </p>
              <p>
                The 150 shared personas support model-level comparison: where Claude and Gemini
                agreed, where they diverged, and whether disagreement correlates with persona
                attributes.
              </p>
              <p>
                The tensions &mdash; places where a persona&apos;s forced-choice, scaled, and
                budget responses pull in different directions &mdash; can be located axis by axis
                and cluster by cluster. That tells us something about which axes the instrument
                measures cleanly and which create internal conflict in respondents.
              </p>
            </div>
          </section>

          {/* Section: What this study cannot support */}
          <section>
            <h2 className="text-[18px] font-serif font-medium text-text-primary mb-3">
              What this study cannot support
            </h2>
            <div className="space-y-4">
              <p>
                These personas are synthetic. The regional and demographic distributions reflect
                how Gemini was prompted to generate them, not the actual distribution of humans in
                those regions. The cluster shares (16% for C0, 21% for C2, and so on) say
                something about the shape of the 12-axis space as traversed by these specific
                personas &mdash; not about the prevalence of any governance philosophy in the real
                world.
              </p>
              <p>
                Per-country analysis runs into the same limit: most countries have too few personas
                to support inference. Regional aggregates are on firmer ground, but
                &ldquo;firmer&rdquo; here means descriptive of this dataset, not extrapolable to
                the populations behind it.
              </p>
              <p>
                The study can tell us about the instrument. It cannot tell us how real populations
                would answer it.
              </p>
            </div>
          </section>

          {/* Section: Download and explore */}
          <section>
            <h2 className="text-[18px] font-serif font-medium text-text-primary mb-3">
              Download and explore
            </h2>
            <div className="space-y-4">
              <p>
                The full dataset is available as a single JSON file:{" "}
                <a
                  href="/data/synthetic_study_v1.json"
                  download
                  className="font-medium text-text-primary underline underline-offset-2 decoration-border-secondary hover:text-text-secondary transition-colors duration-150"
                >
                  Download the dataset ({fileSizeLabel})
                </a>
                . It contains every persona&apos;s demographic attributes, biographical narrative,
                raw responses from both administering models where applicable, scored axis profile,
                cluster assignment, and nearest-archetype mapping.
              </p>
              <p>From here, three pages go deeper:</p>
            </div>

            <div className="mt-6 space-y-3">
              {DEEP_LINKS.map((link) => (
                <Link
                  key={link.href}
                  href={link.href}
                  className="flex items-start justify-between rounded-[8px] border border-border-secondary px-5 py-4 hover:bg-surface-2 transition-colors duration-150 group"
                >
                  <div>
                    <h3 className="text-[17px] font-serif font-medium text-text-primary mb-1">
                      {link.title}
                    </h3>
                    <p className="text-sm text-text-secondary leading-relaxed">
                      {link.description}
                    </p>
                  </div>
                  <span className="ml-4 mt-1 text-text-tertiary group-hover:text-text-secondary transition-colors duration-150 shrink-0">
                    &rarr;
                  </span>
                </Link>
              ))}
            </div>
          </section>
        </div>
      </article>
    </main>
  );
}
